### ISSUE TITLE
New article:  How to do JQ Toggle

### ISSUE THREAD

**Issue by korshunad** [korshunad/frontendForBeginners#15]
- [x] create separate branch like 'article/jquery-toggle'
- [x] create the jquery-toggle.mg in pages (name can be modified, but note that the link on the website will be same as the file name, check other articles for that)
- [x] add article, format it same way as other articles (add author, description, etc), choose category (probably 'tutorials') and tags
- [x] add the preview image to the static folder and to the article
- [x] (optional) add test to tests/server-test.js to check if this new page works
- [x] create a pull request to master and request a review

**Comment by HelloTakako** [comment]
Every tasks done,
Please review, SVP
